### PR TITLE
fix kube-state-metrics make

### PR DESCRIPTION
**Pull request by zhangguanzhang**
等ci跑过后再合并
貌似make 版本问题，避免ci 报错
https://github.com/Loongson-Cloud-Community/dockerfiles/actions/runs/5724953385/job/15512461670

### CODE REVIEW

**Comment by qiangxuhui** [comment]
@zhangguanzhang 
image
两个`builder`？

**Comment by zhangguanzhang** [comment]
等下修复下

**Comment by zhangguanzhang** [comment]
action机器无法拉起代码了

**Comment by zhangguanzhang** [comment]
@qiangxuhui CC

**Comment by qiangxuhui** [comment]
image
修改一下镜像名吧，目前是"gcr"仓库
@zhangguanzhang

**Pull request merged**
