### PR TITLE
update es 7.13.0

### PR DESCRIPTION
**Pull request by yzewei**

### CODE REVIEW

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.13.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwx--x--x usr/libexec/utempter/utempter |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:8.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/sbin/unix_chkpwd |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:8.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/chage |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.13.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwx--x--x usr/libexec/utempter/utempter |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.10.1

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwx--x--x usr/libexec/utempter/utempter |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:8.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/wall |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.13.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/write |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.10.1

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/write |

**Comment by zhangguanzhang** [comment]
```
RUN curl --retry 10 -S -L --output /opt/elasticsearch.tar.gz https://github.com/Loongson-Cloud-Community/elasticsearch/releases/download/v7.10.1/elasticsearch-7.10.1-linux-loongarch64-jdk11-jna5-5-0.tar.gz

RUN tar -zxf /opt/elasticsearch.tar.gz --strip-components=1
```
这俩应该合并成一个RUN并在解压后删掉  `/opt/elasticsearch.tar.gz` ，否则第一个RUN的层里下载的文件，还附带走后面的overlay diff层里大小

**Comment by yzewei** [comment]
@zhangguanzhang 好主意

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:8.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/chage |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.13.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/write |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.10.1

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwx--x--x usr/libexec/utempter/utempter |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.13.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwx--x--x usr/libexec/utempter/utempter |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:v7.3.2

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/write |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.13.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwx--x--x usr/libexec/utempter/utempter |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:8.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/chage |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:v7.3.2

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/write |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:8.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/expiry |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/elasticsearch:7.13.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwx--x--x usr/libexec/utempter/utempter |

**Pull request merged**
