### PR TITLE
feat: 更新 Redis 版本

### PR DESCRIPTION
**Pull request by wojiushixiaobai**

### CODE REVIEW

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:7.0

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/chsh                   |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:7.0-alpine

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | DKL-DI-0004 | FATAL   | Use --no-cache option if use 'apk add': /bin/sh -c set -eux; 		apk add --no-cache --virtual .build-deps 		coreutils 		dpkg-dev dpkg 		gcc 		linux-headers 		make 		musl-dev 		openssl-dev 		wget 	; 		wget -O redis.tar.gz "$REDIS_DOWNLOAD_URL"; 	mkdir -p /usr/src/redis; 	tar -xzf redis.tar.gz -C /usr/src/redis --strip-components=1; 	rm redis.tar.gz; 		grep -E '^ *createBoolConfig[(]"protected-mode",.*, *1 *,.*[)],$' /usr/src/redis/src/config.c; 	sed -ri 's!^( *createBoolConfig[(]"protected-mode",.*, *)1( *,.*[)],)$!\10\2!' /usr/src/redis/src/config.c; 	grep -E '^ *createBoolConfig[(]"protected-mode",.*, *0 *,.*[)],$' /usr/src/redis/src/config.c; 		gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; 	extraJemallocConfigureFlags="--build=$gnuArch"; 	dpkgArch="$(dpkg --print-architecture)"; 	case "${dpkgArch##*-}" in 		amd64 | i386 | x32) extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=12" ;; 		*) extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=16" ;; 	esac; 	extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-hugepage=21"; 	grep -F 'cd jemalloc && ./configure ' /usr/src/redis/deps/Makefile; 	sed -ri 's!cd jemalloc && ./configure !&'"$extraJemallocConfigureFlags"' !' /usr/src/redis/deps/Makefile; 	grep -F "cd jemalloc && ./configure $extraJemallocConfigureFlags " /usr/src/redis/deps/Makefile; 		export BUILD_TLS=yes; 	make -C /usr/src/redis -j "$(nproc)" all; 	make -C /usr/src/redis install; 		serverMd5="$(md5sum /usr/local/bin/redis-server | cut -d' ' -f1)"; export serverMd5; 	find /usr/local/bin/redis* -maxdepth 0 		-type f -not -name redis-server 		-exec sh -eux -c ' 			md5="$(md5sum "$1" | cut -d" " -f1)"; 			test "$md5" = "$serverMd5"; 		' -- '{}' ';' 		-exec ln -svfT 'redis-server' '{}' ';' 	; 		rm -r /usr/src/redis; 		runDeps="$( 		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local 			| tr ',' '\n' 			| sort -u 			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' 	)"; 	apk add --no-network --virtual .redis-rundeps $runDeps; 	apk del --no-network .build-deps; 		redis-cli --version; 	redis-server --version                                                        |
|  1 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  2 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  3 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:6.0

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setgid file: grwxr-xr-x usr/bin/expiry                 |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:7.2

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setgid file: grwxr-xr-x usr/bin/expiry                 |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:6.2

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/su                     |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:7.0

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/passwd                 |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:7.0-alpine

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | DKL-DI-0004 | FATAL   | Use --no-cache option if use 'apk add': /bin/sh -c set -eux; 		apk add --no-cache --virtual .build-deps 		coreutils 		dpkg-dev dpkg 		gcc 		linux-headers 		make 		musl-dev 		openssl-dev 		wget 	; 		wget -O redis.tar.gz "$REDIS_DOWNLOAD_URL"; 	mkdir -p /usr/src/redis; 	tar -xzf redis.tar.gz -C /usr/src/redis --strip-components=1; 	rm redis.tar.gz; 		grep -E '^ *createBoolConfig[(]"protected-mode",.*, *1 *,.*[)],$' /usr/src/redis/src/config.c; 	sed -ri 's!^( *createBoolConfig[(]"protected-mode",.*, *)1( *,.*[)],)$!\10\2!' /usr/src/redis/src/config.c; 	grep -E '^ *createBoolConfig[(]"protected-mode",.*, *0 *,.*[)],$' /usr/src/redis/src/config.c; 		gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; 	extraJemallocConfigureFlags="--build=$gnuArch"; 	dpkgArch="$(dpkg --print-architecture)"; 	case "${dpkgArch##*-}" in 		amd64 | i386 | x32) extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=12" ;; 		*) extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=16" ;; 	esac; 	extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-hugepage=21"; 	grep -F 'cd jemalloc && ./configure ' /usr/src/redis/deps/Makefile; 	sed -ri 's!cd jemalloc && ./configure !&'"$extraJemallocConfigureFlags"' !' /usr/src/redis/deps/Makefile; 	grep -F "cd jemalloc && ./configure $extraJemallocConfigureFlags " /usr/src/redis/deps/Makefile; 		export BUILD_TLS=yes; 	make -C /usr/src/redis -j "$(nproc)" all; 	make -C /usr/src/redis install; 		serverMd5="$(md5sum /usr/local/bin/redis-server | cut -d' ' -f1)"; export serverMd5; 	find /usr/local/bin/redis* -maxdepth 0 		-type f -not -name redis-server 		-exec sh -eux -c ' 			md5="$(md5sum "$1" | cut -d" " -f1)"; 			test "$md5" = "$serverMd5"; 		' -- '{}' ';' 		-exec ln -svfT 'redis-server' '{}' ';' 	; 		rm -r /usr/src/redis; 		runDeps="$( 		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local 			| tr ',' '\n' 			| sort -u 			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' 	)"; 	apk add --no-network --virtual .redis-rundeps $runDeps; 	apk del --no-network .build-deps; 		redis-cli --version; 	redis-server --version                                                        |
|  1 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  2 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  3 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by wojiushixiaobai** [comment]
@qiangxuhui 可能需要重新触发下构建，有两个错误但是不清楚第一个错误是否是构建规则有问题，此项目已经移动按理说不应该走到该流程，最后的错误是无法获取镜像哈希？
```
make: 离开目录“/github-runner/runner/_work/dockerfiles/dockerfiles/library/redis/7.0”
make: *** library/redis/7.0-alpine: No such file or directory。 停止。
make: 进入目录“/github-runner/runner/_work/dockerfiles/dockerfiles/library/redis/7.0”
docker build \
	-t cr.loongnix.cn/library/redis:7.0 \
	-t cr.loongnix.cn/library/redis:7.0-buster \
	-t cr.loongnix.cn/library/redis:7.0.15 \
	-t cr.loongnix.cn/library/redis:7.0.15-buster \
	./debian
Sending build context to Docker daemon  9.728kB
.....
make: 离开目录“/github-runner/runner/_work/dockerfiles/dockerfiles/library/redis/7.0”
1
short_sha: 39817a45d5e7
1
short_sha: 530dc3f1f2ce
扫描镜像: {}
扫描镜像: {}
构建失败 2
Error: Process completed with exit code 2.
```

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:7.0

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setgid file: grwxr-xr-x usr/bin/chage                  |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:7.0-alpine

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | DKL-DI-0004 | FATAL   | Use --no-cache option if use 'apk add': /bin/sh -c set -eux; 		apk add --no-cache --virtual .build-deps 		coreutils 		dpkg-dev dpkg 		gcc 		linux-headers 		make 		musl-dev 		openssl-dev 		wget 	; 		wget -O redis.tar.gz "$REDIS_DOWNLOAD_URL"; 	mkdir -p /usr/src/redis; 	tar -xzf redis.tar.gz -C /usr/src/redis --strip-components=1; 	rm redis.tar.gz; 		grep -E '^ *createBoolConfig[(]"protected-mode",.*, *1 *,.*[)],$' /usr/src/redis/src/config.c; 	sed -ri 's!^( *createBoolConfig[(]"protected-mode",.*, *)1( *,.*[)],)$!\10\2!' /usr/src/redis/src/config.c; 	grep -E '^ *createBoolConfig[(]"protected-mode",.*, *0 *,.*[)],$' /usr/src/redis/src/config.c; 		gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; 	extraJemallocConfigureFlags="--build=$gnuArch"; 	dpkgArch="$(dpkg --print-architecture)"; 	case "${dpkgArch##*-}" in 		amd64 | i386 | x32) extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=12" ;; 		*) extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-page=16" ;; 	esac; 	extraJemallocConfigureFlags="$extraJemallocConfigureFlags --with-lg-hugepage=21"; 	grep -F 'cd jemalloc && ./configure ' /usr/src/redis/deps/Makefile; 	sed -ri 's!cd jemalloc && ./configure !&'"$extraJemallocConfigureFlags"' !' /usr/src/redis/deps/Makefile; 	grep -F "cd jemalloc && ./configure $extraJemallocConfigureFlags " /usr/src/redis/deps/Makefile; 		export BUILD_TLS=yes; 	make -C /usr/src/redis -j "$(nproc)" all; 	make -C /usr/src/redis install; 		serverMd5="$(md5sum /usr/local/bin/redis-server | cut -d' ' -f1)"; export serverMd5; 	find /usr/local/bin/redis* -maxdepth 0 		-type f -not -name redis-server 		-exec sh -eux -c ' 			md5="$(md5sum "$1" | cut -d" " -f1)"; 			test "$md5" = "$serverMd5"; 		' -- '{}' ';' 		-exec ln -svfT 'redis-server' '{}' ';' 	; 		rm -r /usr/src/redis; 		runDeps="$( 		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local 			| tr ',' '\n' 			| sort -u 			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' 	)"; 	apk add --no-network --virtual .redis-rundeps $runDeps; 	apk del --no-network .build-deps; 		redis-cli --version; 	redis-server --version                                                        |
|  1 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  2 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  3 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:6.0

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/chfn                   |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:6.2

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/su                     |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:6.2

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/su                     |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:7.0

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/newgrp                 |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:6.0

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/umount                 |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/redis:7.2

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/newgrp                 |

**Pull request merged**
