### PR TITLE
add es mysql exporter

### PR DESCRIPTION
**Pull request by zhangguanzhang**
```
elasticsearch-exporter:1.7.0
mysqld-exporter:0.15.1
```

### CODE REVIEW

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/elasticsearch-exporter:1.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/mysqld-exporter:0.15.1

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/elasticsearch-exporter:1.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by zhangguanzhang** [comment]
@qiangxuhui PTAL

**Pull request merged**
