### PR TITLE
feat: 更新 Node 版本

### PR DESCRIPTION
**Pull request by wojiushixiaobai**

### CODE REVIEW

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/node:20.8

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setgid file: grwxr-xr-x usr/bin/chage                  |

**Comment by wojiushixiaobai** [comment]
@qiangxuhui  网络问题，需要任意管理重新触发构建。

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/node:18.18

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/newgrp                 |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/node:20.8

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/umount                 |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/node:16.20

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setgid file: grwxr-xr-x usr/bin/chage                  |

**Pull request merged**
