### PR TITLE
修复cadvisor构建失败导致其他镜像没推送

### PR DESCRIPTION
**Pull request by zhangguanzhang**
```
flannel-io/flannel/0.24.4
grafana/loki/2.9.6
kubernetes-sigs/cadvisor/0.49.1
kubernetes/kube-state-metrics/2.11.0
prometheus/alertmanager/0.27.0
prometheus/node-exporter/1.7.0
```

### CODE REVIEW

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/flannel/flannel:v0.24.4

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes-sigs/cadvisor:latest

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| DKL-DI-0006 | WARN | Avoid 'latest' tag |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/grafana/loki:2.9.6

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/node-exporter:1.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/alertmanager:0.27.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/grafana/loki:2.9.6

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/flannel/flannel:v0.24.4

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes/kube-state-metrics:2.11.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/node-exporter:1.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes-sigs/cadvisor:v0.49.1

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/grafana/promtail:2.9.6

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/chsh |

**Comment by zhangguanzhang** [comment]
@qiangxuhui 帮忙合并下

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes/kube-state-metrics:2.11.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/alertmanager:0.27.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/node-exporter:1.7.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/prometheus:2.51.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes-sigs/cadvisor:v0.49.1

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/grafana/promtail:2.9.6

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/passwd |

**Pull request merged**
