### PR TITLE
fix grafana cgo

### PR DESCRIPTION
**Pull request by zhangguanzhang**
grafana 因为 sqlite 问题，必须编译和最终镜像os都要一样，换alpine go镜像编译才可以运行

### CODE REVIEW

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/grafana/grafana:10.0.6

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  1 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/grafana/grafana:10.0.6

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  1 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/grafana/grafana:10.0.6

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  1 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/grafana/grafana:10.0.6

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  1 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by zhangguanzhang** [comment]
@qiangxuhui

**Pull request merged**
