### PR TITLE
Fix codebase size

### PR DESCRIPTION
**Pull request by qiangxuhui**

### CODE REVIEW

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/jaegertracing/jaeger-operator:1.22

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwx--x--x usr/libexec/utempter/utempter |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes/etcd:3.3.12

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0009 | FATAL | Use COPY : /bin/sh -c #(nop) ADD file:0f146d56c7ad7261f3877b353f48d20145bab85d0db441ea3d0c3b2092429122 in /usr/local/bin/  |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by wojiushixiaobai** [comment]
@qiangxuhui 
这样貌似不行老哥，要用 rebase 清理掉之前提交的文件，不然还在历史文件里面。
`git` 如果不用 `--depth` 参数的话还是会拉取这些文件的。

可以参考微软的文档
- [了解如何从 Git 历史记录中移除大型二进制文件，以管理克隆存储库的大小](https://learn.microsoft.com/zh-cn/azure/devops/repos/git/remove-binaries?view=azure-devops)

**Comment by qiangxuhui** [comment]
@wojiushixiaobai 我要先将代码仓哭中比较大的二进制删掉，然后通过工具会去移除`hash-object`中对于这些大文件的引用(大文件会在objects中有压缩的引用记录)。

**Comment by wojiushixiaobai** [comment]
好的，管理员是可以直接覆盖的，普通的用户没法操作这个。

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes/etcd:3.3.12

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/prometheus-operator:0.39.0

| code | level | alerts |
| --- | --- | --- |
| DKL-LI-0001 | SKIP | failed to detect etc/shadow,etc/master.passwd |
| DKL-LI-0002 | SKIP | failed to detect etc/passwd |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/jaegertracing/jaeger-operator:1.22

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/sbin/pam_timestamp_check |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/jaegertracing/jaeger-operator:1.22

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/write |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes/etcd:3.3.12

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/prometheus-operator:0.39.0

| code | level | alerts |
| --- | --- | --- |
| DKL-LI-0001 | SKIP | failed to detect etc/shadow,etc/master.passwd |
| DKL-LI-0002 | SKIP | failed to detect etc/passwd |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/victoriametrics/victoria-metrics:v1.81.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes/etcd:3.3.12

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/jaegertracing/jaeger-operator:1.22

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/gpasswd |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/prometheus-operator:0.39.0

| code | level | alerts |
| --- | --- | --- |
| DKL-LI-0001 | SKIP | failed to detect etc/shadow,etc/master.passwd |
| DKL-LI-0002 | SKIP | failed to detect etc/passwd |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/prometheus-operator:0.39.0

| code | level | alerts |
| --- | --- | --- |
| DKL-LI-0001 | SKIP | failed to detect etc/shadow,etc/master.passwd |
| DKL-LI-0002 | SKIP | failed to detect etc/passwd |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/jaegertracing/jaeger-operator:1.22

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/umount |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes/etcd:3.3.12

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/victoriametrics/victoria-metrics:v1.81.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/victoriametrics/victoria-metrics:v1.81.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/victoriametrics/vmalert:v1.81.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/jaegertracing/jaeger-operator:1.22

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-x--- usr/libexec/dbus-1/dbus-daemon-launch-helper |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/victoriametrics/vmagent:v1.81.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes/etcd:3.3.12

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/victoriametrics/vmauth:v1.81.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/prometheus-operator:0.39.0

| code | level | alerts |
| --- | --- | --- |
| DKL-LI-0001 | SKIP | failed to detect etc/shadow,etc/master.passwd |
| DKL-LI-0002 | SKIP | failed to detect etc/passwd |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/jaegertracing/jaeger-operator:1.22

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/sbin/pam_timestamp_check |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/kubernetes/etcd:3.3.12

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/prometheus/prometheus-operator:0.39.0

| code | level | alerts |
| --- | --- | --- |
| DKL-LI-0001 | SKIP | failed to detect etc/shadow,etc/master.passwd |
| DKL-LI-0002 | SKIP | failed to detect etc/passwd |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/victoriametrics/vmagent:v1.81.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/victoriametrics/vmauth:v1.81.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/victoriametrics/victoria-metrics:v1.81.0

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |

**Pull request merged**
