### PR TITLE
build(openresty): bump openresty/openresty to 1.25.3.1

### PR DESCRIPTION
**Pull request by wojiushixiaobai**

### CODE REVIEW

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/openresty/openresty:1.25.3.1

| code | level | alerts |
| --- | --- | --- |
| DKL-DI-0005 | FATAL | Use 'rm -rf /var/lib/apt/lists' after 'apt-get install|update' : |2 PREFIX_DIR=/usr/local/openresty RUNTIME_DEPENDENCIES=        ca-certificates /bin/sh -c set -ex     && apt-get update     && apt-get install -y --no-install-recommends $RUNTIME_DEPENDENCIES     && apt-get install -y --no-install-recommends $(cat "${PREFIX_DIR}"/DEPENDENCIES)     && sed -i "s@# export @export @g" ~/.bashrc     && sed -i "s@# alias @alias @g" ~/.bashrc |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/wall |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/openresty/openresty:1.25.3.1

| code | level | alerts |
| --- | --- | --- |
| DKL-DI-0005 | FATAL | Use 'rm -rf /var/lib/apt/lists' after 'apt-get install|update' : |2 PREFIX_DIR=/usr/local/openresty RUNTIME_DEPENDENCIES=        ca-certificates /bin/sh -c set -ex     && apt-get update     && apt-get install -y --no-install-recommends $RUNTIME_DEPENDENCIES     && apt-get install -y --no-install-recommends $(cat "${PREFIX_DIR}"/DEPENDENCIES)     && sed -i "s@# export @export @g" ~/.bashrc     && sed -i "s@# alias @alias @g" ~/.bashrc |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/passwd |

**Comment by wojiushixiaobai** [comment]
注意事项：
*) 根据用户需要，可以出一个 `full` tag 的镜像
*) 由于缺少运行环境，[OPM](https://opm.openresty.org/) 和 [LuaRocks](https://luarocks.org/) 会出错，如下：

```sh
opm get spacewander/luafilesystem

Can't locate Encode.pm in @INC (you may need to install the Encode module) (@INC contains: /etc/perl /usr/local/lib/loongarch64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/loongarch64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/loongarch64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/loongarch64-linux-gnu/perl-base) at /usr/local/openresty/bin/opm line 9.
BEGIN failed--compilation aborted at /usr/local/openresty/bin/opm line 9.
```
```sh
luarocks install luafilesystem

PANIC: unprotected error in call to Lua API (...al/openresty/luajit/share/lua/5.1/luarocks/tools/zip.lua:6: module 'zlib' not found:No LuaRocks module found for zlib
	no field package.preload['zlib']
	no file '/usr/local/openresty/luajit/share/lua/5.1/zlib.lua'
	no file '/usr/local/openresty/site/lualib/zlib.ljbc'
	no file '/usr/local/openresty/site/lualib/zlib/init.ljbc'
	no file '/usr/local/openresty/lualib/zlib.ljbc'
	no file '/usr/local/openresty/lualib/zlib/init.ljbc'
	no file '/usr/local/openresty/site/lualib/zlib.lua'
	no file '/usr/local/openresty/site/lualib/zlib/init.lua'
	no file '/usr/local/openresty/lualib/zlib.lua'
	no file '/usr/local/openresty/lualib/zlib/init.lua'
	no file './zlib.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1/zlib.lua'
	no file '/usr/local/share/lua/5.1/zlib.lua'
	no file '/usr/local/share/lua/5.1/zlib/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/zlib/init.lua'
	no file '/root/.luarocks/share/lua/5.1/zlib.lua'
	no file '/root/.luarocks/share/lua/5.1/zlib/init.lua'
	no file '/usr/local/openresty/site/lualib/zlib.so'
	no file '/usr/local/openresty/lualib/zlib.so'
	no file './zlib.so'
	no file '/usr/local/lib/lua/5.1/zlib.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/zlib.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/root/.luarocks/lib/lua/5.1/zlib.so')
```

这属于正常现象，用户需要安装组件要求手动安装依赖：
- https://opm.openresty.org/docs#installation
```sh
# exec your openresty pod
apt-get update
apt-get install -y --no-install-recommends curl perl tar

opm get spacewander/luafilesystem

* Fetching spacewander/luafilesystem  
  Downloading https://opm.openresty.org/api/pkg/tarball/spacewander/luafilesystem-0.1.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6897  100  6897    0     0  13933      0 --:--:-- --:--:-- --:--:-- 13933
Package spacewander/luafilesystem 0.1 installed successfully under /usr/local/openresty/site/ .
```

LuaRocks 问题需要等待 https://github.com/Loongson-Cloud-Community/luajit2 仓库适配 2.1-20231117

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/openresty/openresty:1.25.3.1

| code | level | alerts |
| --- | --- | --- |
| DKL-DI-0005 | FATAL | Use 'rm -rf /var/lib/apt/lists' after 'apt-get install|update' : |2 PREFIX_DIR=/usr/local/openresty RUNTIME_DEPENDENCIES=        ca-certificates /bin/sh -c set -ex     && apt-get update     && apt-get install -y --no-install-recommends $RUNTIME_DEPENDENCIES     && apt-get install -y --no-install-recommends $(cat "${PREFIX_DIR}"/DEPENDENCIES)     && sed -i "s@# export @export @g" ~/.bashrc     && sed -i "s@# alias @alias @g" ~/.bashrc |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/newgrp |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/openresty/openresty:1.25.3.1

| code | level | alerts |
| --- | --- | --- |
| DKL-DI-0005 | FATAL | Use 'rm -rf /var/lib/apt/lists' after 'apt-get install|update' : |2 PREFIX_DIR=/usr/local/openresty RUNTIME_DEPENDENCIES=        ca-certificates /bin/sh -c set -ex     && apt-get update     && apt-get install -y --no-install-recommends $RUNTIME_DEPENDENCIES     && apt-get install -y --no-install-recommends $(cat "${PREFIX_DIR}"/DEPENDENCIES)     && sed -i "s@# export @export @g" ~/.bashrc     && sed -i "s@# alias @alias @g" ~/.bashrc |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/chsh |

**Pull request merged**
