### PR TITLE
py: change COPY to wget to remove the cache in overlay

### PR DESCRIPTION
**Pull request by zhangguanzhang**
dive 分析 py 镜像存在浪费容量
```
dive cr.loongnix.cn/library/python:3.7.10
```
KKLM7POU4 `QPL`W S~Y047
COPY 压缩包换成 wget ，避免overlay的upper层文件附带到镜像里
最好是在 https://github.com/Loongson-Cloud-Community/dockerfiles/issues/25 解决后再合入此pr

### CODE REVIEW

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/python/python3:3.8.0-alpine

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/python/python3:3.8.0-alpine

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/python/python3:3.8.0-alpine

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/python:3.7.10

|    | code        | level   | alerts                                                 |
|---:|:------------|:--------|:-------------------------------------------------------|
|  0 | CIS-DI-0001 | WARN    | Last user should not be root                           |
|  1 | CIS-DI-0005 | INFO    | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
|  2 | CIS-DI-0006 | INFO    | not found HEALTHCHECK statement                        |
|  3 | CIS-DI-0008 | INFO    | setuid file: urwxr-xr-x usr/bin/chsh                   |
|  4 | DKL-LI-0003 | INFO    | Suspicious directory : tmp                             |

**Comment by zhangguanzhang** [comment]
@qiangxuhui PTAL

**Pull request merged**
