### PR TITLE
feat: 更新 MariaDB 版本

### PR DESCRIPTION
**Pull request by wojiushixiaobai**

### CODE REVIEW

**Comment by wojiushixiaobai** [comment]
手动构建没问题，是网络有问题导致的吗？

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/mariadb:10.11

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/mount |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/mariadb:10.11

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/mount |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/library/mariadb:10.11

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/sbin/unix_chkpwd |

**Pull request merged**
