### PR TITLE
build(mc): bump minio/mc to latest

### PR DESCRIPTION
**Pull request by wojiushixiaobai**
This PR is automatically triggered by the GitHub Actions workflow. Please review and verify the changes.

### CODE REVIEW

**Comment by wojiushixiaobai** [comment]
@qiangxuhui 老哥，我没权限重新构建，你点下重新构建看看，我看了下错误是网络问题导致的。

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/gpasswd |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/umount |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/sbin/unix_chkpwd |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/expiry |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/wall |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/newgrp |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/mount |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/umount |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/sbin/unix_chkpwd |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/mount |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setuid file: urwxr-xr-x usr/bin/gpasswd |

**Comment by qiangxuhui** [comment]
- cr.loongnix.cn/minio/minio:RELEASE.2024-05-09T17-04-24Z

| code | level | alerts |
| --- | --- | --- |
| CIS-DI-0001 | WARN | Last user should not be root |
| CIS-DI-0005 | INFO | export DOCKER_CONTENT_TRUST=1 before docker pull/build |
| CIS-DI-0006 | INFO | not found HEALTHCHECK statement |
| CIS-DI-0008 | INFO | setgid file: grwxr-xr-x usr/bin/chage |

**Pull request merged**
